#!/bin/sh
# vim: set ft=sh

set -e -u

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

jq -n "[ { \"random\": \"$(date +%Y%m%d%H%M%S)-${RANDOM}\" } ]" >&3
